w10d01/coffees/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :coffees
  # resources :origins

  resources :origins do
    resources :coffees
  end
end

w10d01/coffees/app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :origin
end

w10d01/coffees/app/models/origin.rb
class Origin < ApplicationRecord
  has_many :coffees
end

w10d01/coffees/app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  def index
    @origin = Origin.find(params[:origin_id])
    @coffees = @origin.coffees
  end
end

w10d01/coffees/app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  def index
    @origins = Origin.all
  end
end

w10d01/coffees/app/helpers/coffees_helper.rb
module CoffeesHelper
end

w10d01/coffees/app/helpers/origins_helper.rb
module OriginsHelper
end

w10d01/coffees/app/views/coffees/index.html.erb
<h1>All the coffees from <%= @origin.origin_name %>!!</h1>

<%= link_to "Origins", origins_path %>

<% @coffees.each do |coffee| %>
  <div class="coffee">
    <h2>Coffee: <%= coffee.blend_name %></h2>
    <h2>Variety: <%= coffee.variety %></h2>
    <h2>Notes: <%= coffee.notes %></h2>
    <h2>Intensifier: <%= coffee.intensifier %></h2>
    <h2>Origin: <%= coffee.origin.origin_name %></h2>
  </div>
<% end %>

w10d01/coffees/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffees</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/coffees/app/views/origins/index.html.erb
<h1>All the origins!!</h1>

<% @origins.each do |origin| %>
  <div class="origin">
    <h2>Origin: <%= origin.origin_name %>
    <h2>View the <%= link_to "coffees", origin_coffees_path(origin) %></h2>
  </div>
<% end %>