w10d01/dune/config/routes.rb
Rails.application.routes.draw do
  resources :stars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :planets, except: [:show, :create]

  # get 'profile', to: 'users#show'

  # resources :planets
  # resources :characters

  resources :planets do
    resources :characters
  end

end

w10d01/dune/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/dune/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :planet
end

w10d01/dune/app/models/planet.rb
class Planet < ApplicationRecord
  has_many :characters
end

w10d01/dune/app/models/star.rb
class Star < ApplicationRecord
end

w10d01/dune/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/dune/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    # req.params.planet_id
    # params[:planet_id]

    @planet = Planet.find(params[:planet_id]) # Planet.find 5
    @characters = @planet.characters
  end
end

w10d01/dune/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
    render json: @planets
  end
end

w10d01/dune/app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: %i[ show edit update destroy ]

  # GET /stars or /stars.json
  def index
    @stars = Star.all
  end

  # GET /stars/1 or /stars/1.json
  def show
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars or /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: "Star was successfully created." }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1 or /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: "Star was successfully updated." }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1 or /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: "Star was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def star_params
      params.fetch(:star, {})
    end
end

w10d01/dune/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/dune/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/dune/app/helpers/planets_helper.rb
module PlanetsHelper
end

w10d01/dune/app/helpers/stars_helper.rb
module StarsHelper
end

w10d01/dune/app/views/characters/index.html.erb
<h1>All the characters from <%= @planet.planet_name %></h1>

<%= link_to "Planets", planets_path %>

<% @characters.each do |character| %>
  <div class="character">
    <h2>Name: <%= character.character_name %></h2>
    <h2>City: <%= character.city %></h2>
    <h2>Title: <%= character.title %></h2>
    <h2>Quote: <%= character.quote %></h2>
    <h2>Planet: <%= character.planet.planet_name %></h2>
  </div>
<% end %>

w10d01/dune/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dune</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/dune/app/views/planets/index.html.erb
<h1>All the planets!!!</h1>

<% @planets.each do |planet| %>
  <div class="planet">
    <h2>Name: <%= planet.planet_name %></h2>
    <h3>Visit the <%= link_to "characters", planet_characters_path(planet) %></h3>
  </div>
<% end %>

w10d01/dune/app/views/stars/_form.html.erb
<%= form_with(model: star) do |form| %>
  <% if star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
        <% star.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/dune/app/views/stars/edit.html.erb
<h1>Editing Star</h1>

<%= render 'form', star: @star %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

w10d01/dune/app/views/stars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stars.each do |star| %>
      <tr>
        <td><%= link_to 'Show', star %></td>
        <td><%= link_to 'Edit', edit_star_path(star) %></td>
        <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star', new_star_path %>

w10d01/dune/app/views/stars/new.html.erb
<h1>New Star</h1>

<%= render 'form', star: @star %>

<%= link_to 'Back', stars_path %>

w10d01/dune/app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>